source 'https://rubygems.org'

gem "pry"
gem "pru"
gem "homesick"
gem "wirble"
gem "gist"

local_gemfile = "~/.Gemfile.local"

if File.exists?(local_gemfile)
  puts "Loading Gemfile.local ..." if $DEBUG # `ruby -d` or `bundle -v`
  instance_eval File.read(local_gemfile)
end
